selcuk couldn't make it
cagataycali/find-mentor pull request #170
Opened 2020-12-15 15:34 UTC by flurach

2020-12-15 15:56 UTC, tansionline commented
LGTM!

2020-12-15 16:00 UTC, cagataycali approved these changes
LGTM as well!

2020-12-15 16:00 UTC, cagataycali commented
What do you think @selimdoyranli

2020-12-15 17:22 UTC, cagataycali commented
Can you provide a screen shot when the project working @flurach

2020-12-15 17:26 UTC, selimdoyranli requested changes

2020-12-15 17:26 UTC, selimdoyranli commented on components/list/ContribList.vue
> +  props: ['contribs', 'size']
propları `required` ve `default` model belirlenen yaklaşımda yazmanı tavsiye ederim. Ek olarak buradaki size prop'unun ismini değiştir. Bu componente yukardan geçtiğin `size` prop'unun neyin size'ı olduğu hiç anlaşılmıyor. `avatarSize` gibi bir isimlendirme tercih edebilirsin.

2020-12-15 17:27 UTC, flurach commented
![Screenshot from 2020-12-15 20-25-41](https://user-images.githubusercontent.com/60688421/102249885-e858e300-3f13-11eb-8dfa-d6519c6b3ee0.png)
![Screenshot from 2020-12-15 20-25-52](https://user-images.githubusercontent.com/60688421/102249893-ea22a680-3f13-11eb-8890-9dd08f94eb4b.png)

2020-12-16 05:38 UTC, flurach commented on components/list/ContribList.vue
> +  <p align="center">
Hocam boyle yapinca disari cikiyor. Nasil sinir verilecegini de bilmiyorum.

![Screenshot from 2020-12-16 08-34-49](https://user-images.githubusercontent.com/60688421/102309514-00634d80-3f7a-11eb-820c-25f28a4518aa.png)

2020-12-16 05:48 UTC, flurach commented on pages/index.vue
> +<style scoped lang="scss">
did this

2020-12-16 05:49 UTC, flurach commented on pages/guide.vue
> +import ContribList from "../components/list/ContribList"
got this one too

2020-12-16 06:41 UTC, selimdoyranli commented on components/list/ContribList.vue
> +  <p align="center">
`<div class="d-flex flex-wrap justify-content-center">...` deneyebilirsin

2020-12-16 06:43 UTC, selimdoyranli approved these changes

2020-12-16 07:19 UTC, merged